### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by himdel** [solderjs/TextEncoderLite#13]
Now that #10 is merged, can we get a npm release newer than 1.0.1 please?

Would love to require this by version, not by commit...

**Comment by himdel** [comment]
(Looks like https://github.com/coolaj86/TextEncoderLite/commit/e1e031b4a7fb89c35629340a61a06ec4f50ce7cb does change package.json, but the npm version was never actually released, or tagged.)

**Comment by nenadvicentic** [comment]
There is version 1.0.1 on npm, but it contains old `text-encoder-lite.js` which does not export `TextEncoderLite` to module system. `text-encoder-lite.min.js` seems to be even older, with no export statement.

**Comment by himdel** [comment]
Judging by https://github.com/coolaj86/TextEncoderLite/commit/e1e031b4a7fb89c35629340a61a06ec4f50ce7cb, the intent was definitely to release 1.0.2.

It's just that nobody ran `npm publish` :)

**Comment by himdel** [comment]
ping @Ruffio ^

**Comment by Ruffio** [comment]
??? I don't have NPM access right. @coolaj86 can you publish NPM?

**Comment by nenadvicentic** [comment]
Hey,

I added pull request #14  where files are exported cleanly in CommonJS format, but also minified `text-encoder-lite.min.js` which is up-to-date with non-minified version. Tried already to import it in my web-project.

**Comment by kpainter-atl** [comment]
This is still an issue over a year later 😞. Is there anyone with write access who can publish the repo?

**Comment by coolaj86** [comment]
Here's how you get want what you want:

> Yo dawg! Will you do us all a favor and run this to cut a new realease?
>
>     git clone https://github.com/solderjs/TextEncoderLite
>     git pull https://github.com/nenadvicentic/TextEncoderLite
>     mversion -m "give the people what they want"
>     npm publish .
>
> Thanks. Additionally, I'd be interested in helping maintain this in the future. If you're interested, add me:
> * Github: @fooperson
> * NPM: @fooperson7

**Comment by coolaj86** [comment]
I just published v2.0.0 because I don't remember what's happened recently (in the last few years) and I figure it's just as well.

**Comment by kpainter-atl** [comment]
Thank you very much 👍
