### ISSUE TITLE
When using Bower, it would be nice with a min version of the js file

### ISSUE THREAD

**Issue by Ruffio** [solderjs/TextEncoderLite#4]

**Comment by coolaj86** [comment]
P.S. This isn't even my project. How did I end up getting MRs on my fork of someone else's deal?

Hmm... I guess I must have published it after them not responding to an MR or something.

Nevertheless, whatever works.

**Comment by Ruffio** [comment]
What do you mean by this isn't your project? It is your fork... Personally I want to use this instead of the master fork as this is much lighter and I'm only interested in utf8. I would have written an issue/suggestion to you about making it a polyfill, so if the browser doesn't support TextEncoder then this would kick in instead. The result would be that if the browser natively supported TextEncoder then that would be used but if not, then this 'project' would be used instead. In that way one can write code as if all browsers has the TextEncoder implemented. I just think that this is too far from your fork as it would break existing implementations that uses the TextEncoderLite instead of TextEncoder.

**Comment by Ruffio** [comment]
Using https://jscompress.com/ the code can be compressed to 1.36 KB. Wow that is really nothing :-)

**Comment by coolaj86** [comment]
Ah, I see what I did here. I probably forked his code in the beginning but then ended up going a different direction and never unlinked the fork.

Please feel free to add the minified version. I think I sent you a collab invite.

**Comment by Ruffio** [comment]
@coolaj86 thanks for the review and merge :-) I don't see the changes. Do you need to update it there or do something?

**Comment by coolaj86** [comment]
Where do you not see the changes? github (I see them)? bower (probably need to push a git tag...)? npm (not updated yet)?

**Comment by coolaj86** [comment]
I just pushed a git tag for bower. And republished on npm.

**Comment by Ruffio** [comment]
Cool, thanks. I see it :-)
![image](https://user-images.githubusercontent.com/1877612/31508395-32906cd2-af7e-11e7-912e-d310d6e5fa81.png)
